# Default Elhub Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

LINTER_RULES_PATH: $HOME/.local/devxp/linters

REPORT_OUTPUT_FOLDER: none #set due to https://github.com/oxsecurity/megalinter/issues/1975

# all, none, or list of linter keys
APPLY_FIXES: none

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
ENABLE_LINTERS:
  - BASH_EXEC
  - BASH_SHELLCHECK
  - GO_GOLANCI_LINT
  - GO_REVIVE
  - JAVA_CHECLSTUØE
  - JAVA_PMD
  - JAVASCRIPT_ES
  - JAVASCRIPT_STANDARD
  - JAVASCRIPT_PRETTIER
  - KOTLIN_KTLINT
  - KOTLIN_DETEKT
  - MAKEFILE_CHECKMAKE
  - POWERSHELL_POWERSHELL
  - POWERSHELL_POWERSHELL_FORMATTER
  - PYTHON_PYLINT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - SQL_SQL_LINT
  - SQL_SQLFLUTT
  - SQL_TSQLLINT
  - TYPESCRIPT_ES
  - TYPESCRIPT_STANDARD
  - TYPESCRIPT_PRETTIER
  - CSS_STYLELINT
  - ENV_DOTENV_LINT
  - HTML_HTMLHHINT
  - JSON_JSONLINT
  - JSON_PRETTIER
  - MARKDOWN_MARKDOWNLINT
  - XML_XMLLINT
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - ANSIBLE_ANSIBLE_LINT
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TERRAGRUNT
  - TERRAFORM_TERRAFORM_FMT

# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
